### ISSUE TITLE
Unable to change meta viewport settings

### ISSUE THREAD

**Issue by vif-maureen** [fishpercolator/revelry#23]
In base.html I want to change the meta viewport settings to allow for user-scalable="yes" with a maximum-scale=2.0.

However making this change in base.html has no effect when building the project. I tried moving the templates directory into my project folder and adjusting the location in project.js to be at the same level as the project but still no luck.

I should mention I'm using jade in this project.

**Comment by pedantic-git** [comment]
Hi @vif-maureen - I'm afraid there's currently no way to change base.html inside your own project. 

What I'll do is make it so that the viewport meta tag is a variable in Revfile.json that can be overridden. I'll try to get this done this week but it's possible it might be next week before I get chance.

[Out of interest, where did you hear about Revelry? I have to admit you're the first person I have heard of using it outside of my own circle of contacts!]

**Comment by vif-maureen** [comment]
Hi @pedantic-git, thanks for the response! I was able to solve it by manually changing it in the generated index.html file but this is not ideal and I do like your solution of adding a property to the JSON file.

I found Revelry by Googling "Reveal.js Jade". 

I am creating a micro-site for my company with content being written by our Marketing team focusing on k-12 education and interconnected learning environments. 

I did one prototype with Reveal.js but there is going to be quite a lot of content with embedded widgets like image carousels, audio playlists, and SVG animations. It became evident that having 1 HTML file was becoming unwieldy and really needed to templatize it somehow.

Revelry is really working out great so far! 

I do have another item on my wish-list for Revelry. If you don't mind, I'll open another issue to see if you have an idea.

Thank you so much for developing this.

**Comment by pedantic-git** [comment]
It's great that it's working for you! In coming back to it just now, I've discovered that Jade is being renamed to Pug so I'll need to get all that changed in the process!

I've made the change you requested and released a 1.1.0 to both npm and Docker Hub. If you go into your project and do a "revelry upgrade" you should now have a "meta" object in your Revfile that you can change.

I would be very interested to see the result of your work with Revelry! And of course, please submit as many feature requests as you like!

**Comment by vif-maureen** [comment]
Thanks so much! I'm aware of the Jade > Pug name change... but since this is working, will it break anything if I pull the changes when you make them?

The site will be launching at the beginning of October so I'll send you the link for sure!

**Comment by pedantic-git** [comment]
When I do implement it, I'll make sure it's all backwards-compatible, and you can use either filename!

Are you happy with the fix in 1.1? I'll close this case if so.

**Comment by vif-maureen** [comment]
Hi @pedantic-git. I ugraded the files however the meta: settings don't show up in the project's Revfile.json. 

If I manually add it, building the project removes it again. I tried it 3 times, twice with my existing project and then with a new test project. Any ideas?

I must be missing something.

**Comment by pedantic-git** [comment]
That sounds potentially like you're still using Revelry v1.0.0. If you type `revelry --version` does it say v1.1.0 ?

**Comment by vif-maureen** [comment]
Thanks, got it! I wasn't the global install. 

Working as expected.

**Comment by pedantic-git** [comment]
Great! Thanks!
